language: java
jdk:
- oraclejdk8
env:
  global:
  - MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=128m"
  - secure: JQZJB7KwydPqR3yAwwXPsXr9D8OmTuMYTZZbvjUC8sscRRyMexoWYtFgvssbfDjVSLrGK3vyC2Ufa+5EuXpw8xR1C/EINnW+/L15wywPgAg8J2Nh76kE8KLUKCpQyYw1zUz9VxJRjnR7CgVTE3UrLXhrf3bQuBmBwOyiiNy7Z0c=
  - secure: PWUKoyPcARaAeJc0TuhWy74FlB+4g4mIV2WTb1hdZFKTtxFsYXN9lyFKrr7Q2osZIcBnp+aDV446kyoBQwx+tMzPLrDC0I8/R9Oo3rl5ochOvblSN2MYmHkleCqNu399OkMQhLSDSmBWiEFZDtVuQLgWsdGIJ+ucPDUhNYUxAPI=
script:
- if [[ "x$TRAVIS_BRANCH" == "xmaster" && "x$TRAVIS_PULL_REQUEST" == "xfalse" ]]; then GOAL=deploy; else GOAL=install; fi
- echo "Goal is " $GOAL
- travis_wait 30 mvn --batch-mode -f parent/pom.xml clean $GOAL
- git remote rm origin
- git remote add origin https://github.com/$TRAVIS_REPO_SLUG
- git fetch origin gh-pages
- git checkout gh-pages
- mvn --batch-mode install
  # - if [[ "x$GOAL" == "xdeploy" ]]; then git fetch --unshakmvn --batch-mode install; fi
