language: java
jdk:
- oraclejdk8
env:
  global:
  - MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=128m"
script:
- if [[ "x$TRAVIS_BRANCH" == "xmaster" && "x$TRAVIS_PULL_REQUEST" == "xfalse" ]]; then GOAL=deploy; else GOAL=install; fi
- echo "Goal is " $GOAL
- mvn --batch-mode -f parent/pom.xml -s settings.xml clean $GOAL
